name: Scheduled Python Script

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    - cron: "0 1 * * *"  # 每天UTC时间1点运行一次，北京时间9点

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # - name: Run Python script
      #   env:
      #     APP_ID: ${{ secrets.APP_ID }}
      #     APP_SECRET: ${{ secrets.APP_SECRET }}
      #     URL: ${{ secrets.URL }}
      #   run: python AutoRelease.py

      - name: Parse secrets and run script
        env:
          FEISHU_SECRET: ${{ secrets.FEISHU_SECRET }}
        run: |
          echo "$FEISHU_SECRET" > config.json
          APP_ID=$(jq -r '.APP_ID' config.json)
          APP_SECRET=$(jq -r '.APP_SECRET' config.json)
          URL=$(jq -r '.URL' config.json)
          echo "APP_ID=$APP_ID"
          # 运行Python脚本并传入环境变量
          APP_ID=$APP_ID APP_SECRET=$APP_SECRET URL=$URL python AutoRelease.py

      - name: Print rel-notes.md content
        run: |
          echo "===== rel-notes.md 内容开始 ====="
          cat rel-notes.md
          echo "===== rel-notes.md 内容结束 ====="

      - name: Configure Git user from secrets
        run: |
          git config user.name "${{ secrets.MY_USER_NAME }}"
          git config user.email "${{ secrets.MY_USER_EMAIL }}"

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          REF_NAME: ${{ github.ref_name }}
        run: |
          git add rel-notes.md
          echo "Repository: $REPOSITORY"
          echo "Ref name: $REF_NAME"
          if ! git diff --cached --quiet; then
            git commit -m "Update rel-notes.md via workflow"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/$REPOSITORY HEAD:$REF_NAME
          else
            echo "No changes to commit"
          fi
