name: Sync rel-notes.md to upstream

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # UTC时间每天2点执行（北京时间10点）

jobs:
  sync-rel-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout upstream repo
        env:
          UPSTREAM_PAT: ${{ secrets.MY_ACCESS_TOKEN }}
          UPSTREAM_REPO: ${{ secrets.TARGET_REPO }}
        run: |
          git clone https://x-access-token:${UPSTREAM_PAT}@github.com/${UPSTREAM_REPO}.git upstream_repo
          cd upstream_repo
          git checkout main

      - name: Compare rel-notes.md files
        id: compare
        run: |
          if cmp -s rel-notes.md upstream_repo/docs/zh/docs/rel-notes.md; then
            echo "files_are_same=true" >> $GITHUB_OUTPUT
          else
            echo "files_are_same=false" >> $GITHUB_OUTPUT
          fi

      - name: Copy rel-notes.md if changed
        if: steps.compare.outputs.files_are_same == 'false'
        run: |
          cp rel-notes.md upstream_repo/docs/zh/docs/rel-notes.md

      - name: Commit and push changes to upstream branch
        if: steps.compare.outputs.files_are_same == 'false'
        env:
          UPSTREAM_PAT: ${{ secrets.MY_ACCESS_TOKEN }}
          UPSTREAM_REPO: ${{ secrets.TARGET_REPO }}
          MY_USER_NAME: ${{ secrets.MY_USER_NAME }}
          MY_USER_EMAIL: ${{ secrets.MY_USER_EMAIL }}
        run: |
          cd upstream_repo
          git config user.name "${MY_USER_NAME}"
          git config user.email "${MY_USER_EMAIL}"
          git checkout -b update-rel-notes || git checkout update-rel-notes
          git add docs/zh/docs/rel-notes.md
          if ! git diff --cached --quiet; then
            git commit -m "Update rel-notes.md via automation"
            git push https://x-access-token:${UPSTREAM_PAT}@github.com/${UPSTREAM_REPO}.git update-rel-notes --force
          else
            echo "No changes to commit"
          fi

      - name: Create Pull Request to upstream
        if: steps.compare.outputs.files_are_same == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.MY_ACCESS_TOKEN }}
          repository: ${{ secrets.TARGET_REPO }}
          base: main
          head: update-rel-notes
          title: "Automated update of rel-notes.md"
          body: "This PR updates rel-notes.md automatically every day."
