name: Sync rel-notes.md to drun-docs

on:
  workflow_dispatch:  # 支持手动触发
  schedule:
    # 这里使用UTC时间，北京时间10点是UTC 2点
    - cron: '0 2 * * *'  # 每天UTC 2点执行，即北京时间10点

jobs:
  sync-rel-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Clone target repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TARGET_REPO_NAME: ${{ secrets.TARGET_REPO_NAME }}
        run: |
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/${TARGET_REPO_NAME}.git target_repo

      - name: Compare rel-notes.md files
        id: compare
        run: |
          if cmp -s rel-notes.md target_repo/docs/zh/docs/rel-notes.md; then
            echo "files_are_same=true" >> $GITHUB_OUTPUT
            cp rel-notes.md target_repo/docs/zh/docs/rel-notes.md
          else
            echo "files_are_same=false" >> $GITHUB_OUTPUT
          fi
          

      - name: Commit and push changes
        if: steps.compare.outputs.files_are_same == 'false'
        run: |
          cd target_repo
          git config user.name "${{ secrets.MY_USER_NAME }}"
          git config user.email "${{ secrets.MY_USER_EMAIL }}"
          git checkout -b update-rel-notes || git checkout update-rel-notes
          git add docs/zh/docs/rel-notes.md
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update rel-notes.md via automation"
            git push origin update-rel-notes --force
          )

      - name: Create Pull Request
        if: steps.compare.outputs.files_are_same == 'false'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: d-run/drun-docs
          base: main
          head: update-rel-notes
          title: "Testing automated update of rel-notes.md, please ignore it."
          body: "This PR updates rel-notes.md automatically every day."
