name: Sync rel-notes.md to drun-docs

on:
  schedule:
    # 这里使用UTC时间，北京时间10点是UTC 2点
    - cron: '0 2 * * *'  # 每天UTC 2点执行，即北京时间10点

jobs:
  sync-rel-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Clone target repo
        env:
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          git clone https://x-access-token:${TARGET_REPO_PAT}@github.com/d-run/drun-docs.git target_repo

      - name: Copy rel-notes.md to target repo
        run: |
          cp rel-notes.md target_repo/docs/zh/docs/rel-notes.md

      - name: Commit and push changes
        env:
          TARGET_REPO_PAT: ${{ secrets.TARGET_REPO_PAT }}
        run: |
          cd target_repo
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git checkout -b update-rel-notes || git checkout update-rel-notes
          git add docs/zh/docs/rel-notes.md
          git diff --quiet && git diff --staged --quiet || (
            git commit -m "Update rel-notes.md via automation"
            git push origin update-rel-notes --force
          )

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.TARGET_REPO_PAT }}
          repository: d-run/drun-docs
          base: main
          head: update-rel-notes
          title: "Automated update of rel-notes.md"
          body: "This PR updates rel-notes.md automatically every day."
